languageCode: 'en-us'
baseUrl: ''
title: 'Gagandeep Singh'
theme: 'ezhil'
paginate: 10
disqusShortname: ''
googleAnalytics: ''
enableRobotsTXT: true

menu:
  main:
    - identifier: home
      name: Home
      title: Home
      url: /
      weight: 1
    - identifier: about
      name: About
      title: About
      url: /about/
      weight: 2
    - identifier: archive
      name: Archive
      title: Archive
      url: /posts/
      weight: 3

params:
  author: 'Gagandeep Singh'
  email: '' # used for microformats
  avatar: '/images/me.png' # used for microformats
  description: ''
  # Uncomment if you need this
  # images:
  #   - images/og-featured.png # relative path to "static" directory
  # customCSS:
  #   - css/my.css # relative path to "assets" directory (don't use main.css filename)
  # customJS:
  #   - js/main.js # relative path to "assets" directory
  dateFormat: '2006-01-02'
  paginationSinglePost: true
  style: auto
  readMore: true
  disableSummary: false
  # utteranc.es support
  utterancesRepo: '' # mandatory
  utterancesTheme: '' # optional
  utterancesIssue: '' # optional
  utterancesLabel: '' # optional
  webmentions:
    url: https://yourdomain.com/webemntions/receive
    login: hugo-theme-anubis
    pingback: true
  social:
    - id: github
      name: pixxstudios
    - id: linkedin
      name: pixxstudios
    - id: instagram
      name: codeandart
#  - id: hugo
#    url: "https://gohugo.io/"
#    icon: "hugo"

markup:
  goldmark:
    renderer:
      unsafe: true # enable raw HTML in Markdown
